### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by Tobyarmond** [DarkstarPhoenix/CMP1903M-A01-2223#1]
Hi Simon,

Like the code so far, especially the enums and overriding the ToString() method in Card.cs that's a nice touch.

I have noticed a couple of things that could be implemented to make things even better though:

1. Have you thought about adding some more comments to your code? Currently they're quite thin on the ground. Using /// can be helpful for making summaries of methods and for explaining their arguments and returns.
2. What if the pack is empty? There doesn't seem to be any checks for this eventuality, so you'll be shuffling an empty pack probably getting index out of range errors. You could throw a custom exception at this point or just throw a generic one like this: `throw new Exception("There are no cards left in the pack!");`
3. Have you thought about adding extra functionality? Maybe a player class which could contain some of the dealt cards?

Keep it up it's coming along well so far!

**Comment by DarkstarPhoenix** [comment]
Toby,

I appreciate the review of my code. 

I have now added more comments describing/explaining more elements with the program, and added more exception methods to catch errors that could come from user inputs.

another class was a good idea. I have now implemented a player class.

Thanks again.
