### ISSUE TITLE
Code review Marco Caçoete - 26492272

### ISSUE THREAD

**Issue by MarcoCacoete** [DarkstarPhoenix/CMP1903M-A01-2223#2]
Hi Simon, looks like you're making a lot of progress on your assignment, good job.

I noticed you don't have a readme associated with your repo, would be a good idea to include to help people to understand your project better, you could also include a txt file in your project with any pseudo code or notes you might want to write throughout the development, it helps to keep your ideas in the same place as where your works is located.

I noticed you have a redundant program class as well as a test class, might be a good idea to remove old files if if they are no longer needed to make sure they don't interfere with how your code runs.

I see you are using enumerations? I don't quite understand how they work, hope you write more comments about the inner workings of this method, so that unexperienced people like me can understand it better.

I noticed you asked for some user input, did you account for empty inputs? In my program that was something I had to deal with using try catch methods I see you used try catch methods somewhere else, maybe it will work here too? I'm not sure if your code accounts for this because of lack of comments.

I see a lot of your methods are public, for encapsulation I believe you should try to make them private in the class.

I hope my suggestions help. Seems like you are well on your way to have a great program here. Kudos.

**Comment by DarkstarPhoenix** [comment]
Marco,

I appreciate the review of my code. I have took your ideas onboard and have implemented additional exception methods, especially where a user interaction is called for. 

Also, I agree that my comments were lacking. I have now added more comments to allow the code to be more readable.

Thanks again.
